### ISSUE TITLE
Reto 1

### ISSUE THREAD

**Issue by skcode7** [delineas/retos-livechallenge#1]
Tengo una duda, se pide listar las paradas del metro. 
Pero si no estoy entendiendo mal, para **metro** lo que existen son **estaciones**

Estoy en lo correcto?

**Comment by delineas** [comment]
Ups! No me avisó de la issue el correo, sorry.

Efectivamente, son estaciones
https://developer.tmb.cat/api-docs/v1/transit#tag/Estacions

Gracias!
